name: Test Action
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Download Hugo
        uses: ./
        with:
          repo-name: 'gohugoio/hugo'
          file-name: 'hugo_extended_.*_{{SYSTEM}}-{{ARCH}}\.tar\.gz'
          use-regex: 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Verify Installation
        run: |
          hugo version
